export const skillsData = [ 'Adveturous', 
    'Autonomous', 
    'Bold', 
    'Collaborative', 
    'Curious', 
    'Design Driven', 
    'Ego-Free', 
    'Empathetic', 
    'Empowering', 
    'Entrepreneurial', 
    'Fast Paced',
    'Focused',
    'Foward Thinking',
    'Inclusive',
    'Purposeful'
];